<?php

use yii\widgets\Breadcrumbs;

if(!empty($this->context->current_cat->meta_desc)){
	$this->registerMetaTag(['name' => 'description', 'content' => $this->context->current_cat->meta_desc]);
}
if(!empty($this->context->current_cat->meta_keys)){
	$this->registerMetaTag(['name' => 'keywords', 'content' => $this->context->current_cat->meta_keys]);
}
if(!empty($this->context->current_cat->meta_title)){
	$this->title = $this->context->current_cat->meta_title;
}else{
	$this->title = $this->context->current_cat->title;
}
$this->params['breadcrumbs'][] = ['label' => 'Life Insurance', 'url' => '/life-insurance/'];
$this->params['breadcrumbs'][] = $this->context->current_cat->title;
?>
<div class="page-content page-wrapper trans_all">

	<!-- START PAGE-CONTENT -->
	<section class="page">
    <!-- <aside>
			<div class="sticky-block">
				<h2>Jump to a section</h2>
				<ul>
					<li><a href="#whatisit">What is it?</a></li>
					<li><a href="#whatinfo">What Info do the Have?</a></li>
                    <li><a href="#why">Why Do Life Insurance Companies Check Credit?</a></li>
                    <li><a href="#check">How to Check Your Report</a></li>
                    <li><a href="#what">What Reports Do Life Insurance Companies Check?</a></li>
				</ul>
			</div>
	</aside> -->
		<article class="content">
			<h1>What is LexisNexis Used for in Life Insurance?</h1>
			<!-- <?=Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]);?> -->
			<?=$this->render('/main/widgets/authors-small.php', ['updated' => date('F j, Y', filemtime(__FILE__))]);?>
            <p><strong>You're being evaluated on several factors when you apply for a life insurance policy</strong>. Insurance companies have underwriting standards. They'll compare your information against those standards to assess how much of a risk you are. From there, you'll either be offered a coverage price or your application will be declined.<strong> The insurance company doesn't just look at what you put down on your application</strong>. In many cases,<strong> the company will pull additional information about you from a consumer reporting agency.</strong> One of the companies that provides this info is <a href="https://risk.lexisnexis.com/">LexisNexis</a>.</p>
            
            <h2 id="whatisit">What is Lexis Nexis?</h2>
            <blockquote class="green">LexisNexis is a data repository. They collect and analyze information from other smaller databases and reporting agencies. <strong>A division of the company called LexisNexis Risk Solutions provides this information to companies in the form of a credit report and score.</strong></blockquote>
            
            <h2 id="whatinfo">What Information Does LexisNexis Provide to Insurance Companies?</h2>
            <p>LexisNexis uses its databases to calculate an insurance score. <strong>Your insurance score represents how likely you are to file an insurance claim based on your past habits</strong>. Companies use this score in combination with other factors on your application to determine if they can approve you and at what rate. Your score will also include what is a "reason code." Reason codes are the primary factors that influenced your score.</p>
            <h3>Is a LexisNexis Report the Same as a Credit Report?</h3>
            <p>LexisNexis is a type of credit report. Most people think of credit reports as the information that comes from the three major credit reporting bureaus: Transunion, Equifax, and Experian. However, <strong>there are actually </strong><a href="https://files.consumerfinance.gov/f/documents/cfpb_consumer-reporting-companies-list.pdf"><strong>49 different credit reports</strong></a><strong> that can be pulled when you seek approval for various financial products or during employment screening. </strong></p>
            <p><strong>The score generated by LexisNexis is called an insurance score</strong>. Your insurance score is not the same as the credit score used when you apply for a credit card or loan. <strong>An insurance score adds in additional information and weighs items differently than a standard credit report.</strong> Your LexisNexis report includes any:</p>
            <ul>
            <li>Bankruptcies</li>
            <li>Liens</li>
            <li>Criminal offenses</li>
            <li>Mortgages</li>
            <li>Property ownership</li>
            <li>Weapons license</li>
            <li>Professional license</li>
            </ul>
            <p>The insurance underwriters will take all of this information into account when offering you a policy.<strong> In some instances, information on your LexisNexis report could prevent you from getting approved.</strong> For example, some life insurance companies won't grant policies to people who've declared bankruptcy within the last 12 to 24 months. You might also have trouble obtaining a policy if you're currently being <a href="https://www.noexam.com/life-insurance/felons/">charged with a felony</a> or if you've recently been released from jail.</p>
            <h3>What Information Doesn't LexisNexis Provide?</h3>
            <p>Your LexisNexis report does not contain your:</p>
            <ul>
            <li>Race</li>
            <li>Religion</li>
            <li>Age</li>
            <li>Gender</li>
            <li>National origin</li>
            <li>Marital status</li>
            <li>Disability</li>
            <li>Occupation</li>
            <li>Employer information</li>
            <li>Address</li>
            </ul>
            <p>However, you'll provide many of those variables yourself when you're <a href="https://www.noexam.com/life-insurance/approval-time/">applying for a life insurance policy</a>. It might all seem like a lot of information, but <strong>insurance underwriters want to make sure that offering you a policy makes financial sense for the company.</strong></p>
            
            <h2 id="why">Why Do Life Insurance Companies Check Credit?</h2>
            <p>Insurance companies use credit information to calculate the risk of offering you a policy<strong>. </strong><a href="http://www.scorgloballifeamericas.com/en-us/knowledgecenter/Pages/LexisNexisRiskClassifierPreview.pdf"><strong>A pattern of risky financial behavior is associated with a higher risk of mortality</strong></a><strong>. </strong>This means that people with a low score are a greater risk to the insurance company.&nbsp;</p>
            
            <h2 id="check">Can I Check My LexisNexis Report?</h2>
            <p>Yes. <strong>You can order a free copy of your LexisNexis report once a year.</strong> There are three options to obtain your report:</p>
            <ul>
            <li>By Phone: 866-897-8126</li>
            <li>By Mail: LexisNexis Consumer Center, Attn: Full File Disclosure, P.O. Box 105108, Atlanta, GA 30348-5108</li>
            <li>Online: By <a href="https://personalreports.lexisnexis.com/access_your_full_file_disclosure.jsp">filling out this form</a>.</li>
            </ul>
            <p>You'll need to provide your full name, Social Security number, current address, and date of birth in order to receive your report. You can dispute any information in your report that isn't accurate. LexisNexis will investigate your claim and remove the information if it's found to be incorrect.</p>
            
            <h2 id="what">What Reports Do Life Insurance Companies Check?</h2>
            <p><strong>Most companies will pull your information from a few different sources to get a complete picture of your financial and lifestyle habits</strong>. In addition to your LexisNexis report, many companies will do what is known as a "soft pull" of your general credit. A soft pull provides information to companies without costing you points off your credit score. Underwriters might also pull your:</p>
            <ul>
            <li><strong>Driving Records</strong> &mdash; Your rates might go up if you have a history of auto accidents, speeding tickets, or reckless driving.</li>
            <li><strong>Prescription Drug History </strong>&mdash; The medicines you take and their doses can provide a window into your health and symptom management. Underwriters can use this information to assess your risk.</li>
            <li><strong>Medical Records</strong> &mdash; In some cases, an insurance company might request your medical records in addition to having you <a href="https://www.noexam.com/life-insurance/health-exam/">take a medical exam.</a></li>
            <li><strong>Fill Criminal Reports</strong> &mdash; The insurance company might pull criminal information beyond what is provided by LexisNexis for underwriting.</li>
            <li><strong>Your Medical Information Bureau (MIB) Report</strong> &mdash; Your MIB report contains information about any past life insurance applications you've made. MIB reports show what was found the last time you applied for insurance so that underwriters can compare it to the information you provided this time. This doesn't mean you'll be rejected if you've shopped around for insurance in the past or decided not to take a policy you were offered. MIB reports are looking for fraud and inconsistencies, not the number of applications you've made.</li>
            </ul>
            
            <h2>Final Thoughts</h2>
            <p>It's important to be honest on your life insurance application. It might seem tempting to leave out information in the hopes of getting a lower rate, but it's not worth the risk. As you can see, Insurance companies have ways of checking for fraud. There's a good chance they'll find out if your application wasn't accurate. A company that was willing to work with you is a lot more likely to reject your application if they have to find the information on their own.</p>
            <p>You can order a copy of your LexisNexis report so you can see what the insurance company does. If you're concerned your financial or other history might prevent you from getting a policy, reach out to one of our trained agents. We can help find companies that will fit your circumstances and offer you a policy even if you're a <a href="https://www.noexam.com/life-insurance/high-risk/">high-risk candidate</a>.</p>
           
		</article>
	</section>
	<!-- END PAGE-CONTENT -->

	<section class="related-articles">
		<?=$this->render('/main/widgets/related-articles.php');?>
	</section>
</div>
<?=$this->render('/main/widgets/bio-jonathan-holloway.php'); //Bio Embed Code?>
