<?php
$config = [
	'options' => [
		'rows' => 40,
	],
	'language' => 'en',
	'clientOptions' => [
		'plugins' => [
			"advlist",
			"anchor",
			"autolink",
			"autoresize",
			#"autosave",
			#"bbcode",
			"charmap",
			"code",
			"codesample",
			"colorpicker",
			"contextmenu",
			#"directionality",
			#"emoticons",
			"filemanager",
			#"fullpage",
			"fullscreen",
			#"help",
			"hr",
			"image",
			"imagetools",
			#"importcss",
			"insertdatetime",
			#"legacyoutput",
			"link",
			"lists",
			"media",
			#"nonbreaking",
			"pagebreak",
			"paste",
			#"preview",
			#"print",
			#"quickbars",
			"responsivefilemanager",
			#"save",
			#"searchreplace",
			#"spellchecker",
			#"tabfocus",
			"table",
			#"template",
			#"textcolor",
			#"textpattern",
			#"toc",
			"visualblocks",
			#"visualchars",
			#"wordcount",
		],
		'skin' => 'oxide-dark',
		'content_css' => 'default',
		'theme' => 'silver',
		'paste_data_images' => true,
		'a11y_advanced_options' => true,
		#'file_picker_callback' => new JsExpression('jsFunctionToBeCalled'),
		'file_picker_types' => 'file image media',
		'block_unsupported_drop' => false,
		'image_advtab' => true,
		'image_caption' => true,
		'image_description' => true,
		'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | hr | link image responsivefilemanager",
		'external_filemanager_path' => '/plugins/responsive_filemanager/filemanager/',
		'filemanager_title' => 'Responsive Filemanager',
		'external_plugins' => [
			// Кнопка загрузки файла в диалоге вставки изображения.
			'filemanager' => '/plugins/responsive_filemanager/filemanager/plugin.min.js',
			// Кнопка загрузки файла в тулбаре.
			'responsivefilemanager' => '/plugins/responsive_filemanager/tinymce/plugins/responsivefilemanager/plugin.min.js',
		]
	]
];

return $config;